language: python

python:
  - 3.6
  - 3.5

before_install:
  - sudo apt-get install pandoc

install:
  - pip install tox tox-travis

script:
  - tox

after_script:
  - pip install codecov
  - codecov
